<a href="https://colab.research.google.com/github/NINJAHATTORI004/programmingwithdataanalysis/blob/main/programmingwithdataanalysis_tf_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Basic Numpy Array Creation

import numpy as np

# 1D array
arr1 = [1, 2, 3]
narr1 = np.array(arr1)
print("Type of narr1:", type(narr1))

# Multidimensional array
arr2 = [[1, 2, 3, 4], [3, 4, 5, 6]]
narr2 = np.array(arr2)
print("narr2:\n", narr2)

# 3D array
arr3 = [[[1, 2, 3, 4], [3, 4, 5, 6], [7, 8, 9, 6]]]
narr3 = np.array(arr3)
print("narr3:\n", narr3)
print("Shape of narr3:", narr3.shape)

# 2x2 array filled with 0s
zer = np.zeros((2, 2))
print("2x2 array with 0s:\n", zer)

# 2x2 array filled with 5s
full = np.full((2, 2), 5)
print("2x2 array with 5s:\n", full)

# Identity matrix (2x2)
ex3 = np.eye(2, 2)  # diagonal 1
print("2x2 Identity matrix:\n", ex3)

# Optional: 4x4 identity matrix
ex4 = np.eye(4, 4)  # diagonal 1
print("4x4 Identity matrix:\n", ex4)



Type of narr1: <class 'numpy.ndarray'>
narr2:
 [[1 2 3 4]
 [3 4 5 6]]
narr3:
 [[[1 2 3 4]
  [3 4 5 6]
  [7 8 9 6]]]
Shape of narr3: (1, 3, 4)
2x2 array with 0s:
 [[0. 0.]
 [0. 0.]]
2x2 array with 5s:
 [[5 5]
 [5 5]]
2x2 Identity matrix:
 [[1. 0.]
 [0. 1.]]
4x4 Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:

# Multi-dimensional array operations

import numpy as np

# Define a 2D array with consistent sublist lengths
arr = [[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 6, 0, 0],  # Padded with 0s to match length
       [12, 7, 10, 9, 0, 0],  # Padded with 0s to match length
       [2, 11, 8, 10, 0, 0]]  # Padded with 0s to match length

# Convert to numpy array
narr = np.array(arr)

# Print the full array
print("Original array:\n", narr)

# Print first row (row index 0)
print("First row:", narr[0])

# Print value at row index 2, column index 3
print("Value at [2,3]:", narr[2, 3])

# Replace a value at a location
narr[3, 0] = 14
print("Modified array:\n", narr)

# Get the last row
print("Last row:", narr[-1])

# Get the second last row
print("Second last row:", narr[-2])

# Print specific rows and columns
# Rows: from index 1 to 3 (4 is excluded)
# Columns: from index 2 to 4 (5 is excluded)
print("Sliced array (rows 1-3, columns 2-4):\n", narr[1:4, 2:5])

# Concatenation row and column wise

# Define arrays to concatenate
a = np.array([[1, 2, 3, 4]])
b = np.array([[5, 6]])

# Concatenate row-wise
# c = np.concatenate((a, b))  # This will still result in an error due to inconsistent shapes
# print("Row-wise concatenation:\n", c)
# To concatenate, make sure the arrays have compatible shapes. For example:
b = np.array([[5, 6, 0, 0]])  # Padded with 0s to match length
c = np.concatenate((a, b))
print("Row-wise concatenation:\n", c)


Original array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9  6  0  0]
 [12  7 10  9  0  0]
 [ 2 11  8 10  0  0]]
First row: [1 2 3 4 5 6]
Value at [2,3]: 9
Modified array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9  6  0  0]
 [12  7 10  9  0  0]
 [14 11  8 10  0  0]]
Last row: [14 11  8 10  0  0]
Second last row: [12  7 10  9  0  0]
Sliced array (rows 1-3, columns 2-4):
 [[ 9  6  0]
 [10  9  0]
 [ 8 10  0]]
Row-wise concatenation:
 [[1 2 3 4]
 [5 6 0 0]]


In [6]:
# Import necessary libraries
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.utils import to_categorical

# Load MNIST dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Preprocess data
x_train = x_train.reshape(60000, 784).astype('float32') / 255
x_test = x_test.reshape(10000, 784).astype('float32') / 255
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

# Build neural network model
model = Sequential()
model.add(Dense(512, activation='relu', input_shape=(784,)))
model.add(Dropout(0.2))
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(10, activation='softmax'))

# Compile model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train model
model.fit(x_train, y_train, batch_size=128, epochs=5, validation_data=(x_test, y_test))

# Evaluate model
score = model.evaluate(x_test, y_test)
print('Test accuracy:', score[1])


11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 11s 21ms/step - accuracy: 0.8633 - loss: 0.4546 - val_accuracy: 0.9656 - val_loss: 0.1056
Epoch 2/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 10s 20ms/step - accuracy: 0.9662 - loss: 0.1064 - val_accuracy: 0.9741 - val_loss: 0.0825
Epoch 3/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 10s 20ms/step - accuracy: 0.9768 - loss: 0.0751 - val_accuracy: 0.9782 - val_loss: 0.0669
Epoch 4/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 10s 20ms/step - accuracy: 0.9827 - loss: 0.0518 - val_accuracy: 0.9819 - val_loss: 0.0605
Epoch 5/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 10s 21ms/step - accuracy: 0.9856 - loss: 0.0438 - val_accuracy: 0.9816 - val_loss: 0.0653
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9769 - loss: 0.0811
Test accuracy: 0.9815999865531921
