<a href="https://colab.research.google.com/github/NINJAHATTORI004/programmingwithdataanalysis/blob/main/Tensorflow_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf


1. creating tensors as constants


In [ ]:
#creating a scaler (0D Tensors)
scaler = tf.constant(11)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=11>

In [ ]:
vector=tf.constant([1,2 ])
print(vector)


tf.Tensor([1 2], shape=(2,), dtype=int32)


In [ ]:
#2d tensors
matrix=tf.constant([[1,2],[3,4]])
print(matrix)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [ ]:
#creating a 3D tensor
tensor=tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
print(tensor)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


creating tensors with tf.variable

In [ ]:
variable_tensor=tf.Variable([1.0,2.0],[3.0,4.0])
print(variable_tensor)

In [ ]:
import tensorflow as tf

#Scaler (0D tensors)
scaler_var=tf.Variable(42)

vector_var=tf.Variable([1.0,2.0,3.0])

matrix_var=tf.Variable([[1.0,2.0],[3.0,4.0]])

tensor_var=tf.Variable([[[1.0,2.0],[3.0,4.0]],[[5.0,6.0],[7.0,8.0]]])

print("Scaler Variable:", scaler_var)
print("Vector Variable:", vector_var)
print("Matrix Variable:", matrix_var)
print("Tensor Variable:", tensor_var)

Scaler Variable: <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>
Vector Variable: <tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>
Matrix Variable: <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>
Tensor Variable: <tf.Variable 'Variable:0' shape=(2, 2, 2) dtype=float32, numpy=
array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]], dtype=float32)>


3. Creating tensors using tf.zeros(), tf.ones(), and tf.fill()  

In [ ]:
#creating a tensor filled with zeros
zeros_tensor=tf.zeros([2,3])
ones_tensor=tf.ones([2,3])
zeros_tensors_3d=tf.zeros([2,3,4])


print("Zeros Tensor:", zeros_tensor)
print("Ones Tensor:", ones_tensor)
print("zeros 3d tensor:",zeros_tensors_3d)

Zeros Tensor: tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
Ones Tensor: tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
zeros 3d tensor: tf.Tensor(
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]], shape=(2, 3, 4), dtype=float32)


In [ ]:
#4. creating tensorsflow as tf
range_tensor_=tf.range(10)
range_tensor_step=tf.range(3,12,2)


print("Range Tensor:", range_tensor_)
print("Range Tensor with Step:", range_tensor_step)


Range Tensor: tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
Range Tensor with Step: tf.Tensor([ 3  5  7  9 11], shape=(5,), dtype=int32)


In [ ]:
import tensorflow as tf
tensor=tf.constant([[1,2,3],[4,5,6]])
print("shape:",tensor.shape)
print("data type:",tensor.dtype)
print(tf.rank(tensor))


shape: (2, 3)
data type: <dtype: 'int32'>
tf.Tensor(2, shape=(), dtype=int32)


defining sequential model


In [ ]:

from tensorflow.keras import Sequential
from tensorflow.keras import layers

model=Sequential([
    layers.Dense(6,activation="relu", input_shape=(4,)),
    layers.Dense(1,activation="sigmoid")

])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
from tensorflow.keras.layers import Flatten

flatten_layer=Flatten()

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

model=keras.Seqential([
    layer
])

In [ ]:
import tensorflow as tf

# Define the CNN model
model = tf.keras.models.Sequential([
  tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
  tf.keras.layers.MaxPooling2D((2, 2)),
  tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
  tf.keras.layers.MaxPooling2D((2, 2)),
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(10, activation='softmax')
])

# Print the model summary
model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                      │ (None, 26, 26, 32)          │             320 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d (MaxPooling2D)         │ (None, 13, 13, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 11, 11, 64)          │          18,496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_1 (MaxPooling2D)       │ (None, 5, 5, 64)            │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_1 (Flatten)                  │ (None, 1600)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 10)                  │          16,010 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 34,826 (136.04 KB)

 Trainable params: 34,826 (136.04 KB)

 Non-trainable params: 0 (0.00 B)